# Generated by Django 3.2.3 on 2021-08-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_alter_transfers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
